name: backend
description: Backend API para aplicativo veterinário usando Dart Frog
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  dart_frog: ^2.0.0
  dart_jsonwebtoken: ^2.14.0
  bcrypt: ^1.1.3
  csv: ^6.0.0

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.24.0
